---
image: ubuntu:18.04

build:
  before_script:
    - apt-get update -y -q
    - apt-get install -y -q --no-install-recommends cmake make g++ libfontconfig1-dev libsfml-dev
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc --ignore=1)
