---
image: ubuntu:18.04

build:
  before_script:
    - apt-get update -y -q
    - apt-get install -y -q --no-install-recommends cmake make g++ libfontconfig1-dev libsfml-dev
  script:
    # - wget https://angelcode.com/angelscript/sdk/files/angelscript_2.32.0.zip
    # - unzip angelscript_2.32.0.zip
    # - make -j$(nproc --ignore=1) -C sdk/angelscript/projects/gnuc
    # - make -C sdk/angelscript/projects/gnuc install
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc --ignore=1)
